/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'total' : Price,
  'clientId' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'itemId' : string,
  'quantity' : bigint,
  'price' : Price,
}
export interface Price { 'currency' : string, 'amount' : number }
export interface Product {
  'id' : string,
  'title' : string,
  'sourceUrl' : string,
  'price' : Price,
  'rawPayload' : string,
}
export interface Service {
  'id' : string,
  'title' : string,
  'sourceUrl' : string,
  'price' : Price,
  'rawPayload' : string,
}
export interface _SERVICE {
  'createOrder' : ActorMethod<[Order], string>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'echoText' : ActorMethod<[string], string>,
  'generateClientId' : ActorMethod<[string, string], string>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getArbitrages' : ActorMethod<[], Array<[string, Price, string, Price]>>,
  'getContactInfo' : ActorMethod<[], [string, string]>,
  'getOrder' : ActorMethod<[string], Order>,
  'getOrdersByClient' : ActorMethod<[string], Array<Order>>,
  'getProductsByCurrency' : ActorMethod<[string], Array<Product>>,
  'getProductsByMinPrice' : ActorMethod<[number], Array<Product>>,
  'getProductsBySource' : ActorMethod<[string], Array<Product>>,
  'getProductsSortedByPrice' : ActorMethod<[], Array<Product>>,
  'getSitemap' : ActorMethod<[], Array<[string, bigint, string]>>,
  'setArbitrage' : ActorMethod<
    [string, [string, Price, string, Price], [string, Price, string, Price]],
    bigint
  >,
  'updateOrder' : ActorMethod<[string, Order], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];