/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Price = IDL.Record({
  'currency' : IDL.Text,
  'amount' : IDL.Float64,
});
export const OrderItem = IDL.Record({
  'itemId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : Price,
});
export const CreateOrderRequest = IDL.Record({
  'clientId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sourceUrl' : IDL.Text,
  'price' : Price,
  'rawPayload' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sourceUrl' : IDL.Text,
  'price' : Price,
  'rawPayload' : IDL.Text,
});
export const Order = IDL.Record({
  'total' : Price,
  'clientId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'createOrder' : IDL.Func([CreateOrderRequest], [IDL.Text], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'echoText' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getArbitrages' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Price, IDL.Text, Price))],
      ['query'],
    ),
  'getContactInfo' : IDL.Func([], [IDL.Text, IDL.Text], []),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getOrderTrace' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getOrdersByClient' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProductsByCurrency' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByMinPrice' : IDL.Func(
      [IDL.Float64],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsBySource' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSitemap' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Text))],
      [],
    ),
  'setArbitrage' : IDL.Func(
      [
        IDL.Text,
        IDL.Tuple(IDL.Text, Price, IDL.Text, Price),
        IDL.Tuple(IDL.Text, Price, IDL.Text, Price),
      ],
      [IDL.Nat],
      [],
    ),
  'updateOrder' : IDL.Func([IDL.Text, Order], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Price = IDL.Record({ 'currency' : IDL.Text, 'amount' : IDL.Float64 });
  const OrderItem = IDL.Record({
    'itemId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : Price,
  });
  const CreateOrderRequest = IDL.Record({
    'clientId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sourceUrl' : IDL.Text,
    'price' : Price,
    'rawPayload' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sourceUrl' : IDL.Text,
    'price' : Price,
    'rawPayload' : IDL.Text,
  });
  const Order = IDL.Record({
    'total' : Price,
    'clientId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'createOrder' : IDL.Func([CreateOrderRequest], [IDL.Text], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'echoText' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getArbitrages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Price, IDL.Text, Price))],
        ['query'],
      ),
    'getContactInfo' : IDL.Func([], [IDL.Text, IDL.Text], []),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getOrderTrace' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getOrdersByClient' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProductsByCurrency' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByMinPrice' : IDL.Func(
        [IDL.Float64],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsBySource' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSitemap' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Text))],
        [],
      ),
    'setArbitrage' : IDL.Func(
        [
          IDL.Text,
          IDL.Tuple(IDL.Text, Price, IDL.Text, Price),
          IDL.Tuple(IDL.Text, Price, IDL.Text, Price),
        ],
        [IDL.Nat],
        [],
      ),
    'updateOrder' : IDL.Func([IDL.Text, Order], [], []),
  });
};

export const init = ({ IDL }) => { return []; };